depot:
    path: /depot
    controller: App\Controller\DepotController::Depot
    methods: POST

login_check:
    path: /login_check
    methods: [POST]

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
