<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8YGxxLk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8YGxxLk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8YGxxLk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8YGxxLk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8YGxxLk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8YGxxLk',
    'container.build_id' => '20a152c3',
    'container.build_time' => 1581979177,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8YGxxLk');
