<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDSJ87Qd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDSJ87Qd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDSJ87Qd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDSJ87Qd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDSJ87Qd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DSJ87Qd',
    'container.build_id' => 'a5438bc9',
    'container.build_time' => 1582408842,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDSJ87Qd');
