<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKx2xs8J\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKx2xs8J/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKx2xs8J.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKx2xs8J\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKx2xs8J\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Kx2xs8J',
    'container.build_id' => 'fadf6acf',
    'container.build_time' => 1582221227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKx2xs8J');
